version: "2.4"

## ISLE 8 Draft Prototype
## Feb, 2020
## MVP 1 - Traefik, Solr, MySQL & Drupal (using Woodby images for Apache, Drupal and Solr)
## MVP 2 - Microservices & Connectors (Houdini, Homarus, Hypercube, FITS, ActiveMQ and Cantaloupe)

services:
  mariadb:
    image: mariadb:10.3.22
    environment:
      MYSQL_DATABASE: ${DB_NAME:-islandora}
      MYSQL_USER: ${DB_USER:-islandora}
      MYSQL_PASSWORD: ${DB_PASSWORD:-dbpassword}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-dbpassword}
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      # https://dev.mysql.com/doc/refman/8.0/en/mysqladmin.html#command_mysqladmin_ping
      test: ["CMD", "mysqladmin", "ping", "--silent"]

  drupal:
    build:
      context: ./
      dockerfile: ${PROJECT_DRUPAL_DOCKERFILE:-./drupal.Dockerfile}
      target: dev
      args:
        - code_dir=./codebase
        - base_image_tag=7.2.28-1.17.8-0ceedc1b
        - build_environment=dev
        - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE:-UTC}
        # XDEBUG confd build time args - you can set it to 0 turn it off.
        - PHP_XDEBUG=${PHP_XDEBUG:-1}
        - PHP_IDE_CONFIG="serverName=${PHP_IDE_CONFIG_SERVER_NAME:-idcp.localhost}"
        - PHP_XDEBUG_REMOTE_HOST=${PHP_XDEBUG_REMOTE_HOST:-host.docker.internal}
        - PHP_XDEBUG_DEFAULT_ENABLE=${PHP_XDEBUG_DEFAULT_ENABLE:-1}
        - PHP_XDEBUG_REMOTE_CONNECT_BACK=${PHP_XDEBUG_REMOTE_CONNECT_BACK:-0}
        # NGINX confd build time args
        - NGINX_SERVER_ROOT=${APP_DOCROOT:-/var/www/app/web}
        - NGINX_LISTEN_PORT=8080
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      APP_NAME: ${DRUPAL_SITE_NAME:-islandora}
      APP_ROOT: ${APP_ROOT:-/var/www/app}
      APP_ACCOUNT_NAME: ${DRUPAL_USER_NAME:-islandora}
      APP_ACCOUNT_MAIL: ${DRUPAL_USER_EMAIL:-islandora@example.com}
      DB_NAME: ${DB_NAME:-drupal}
      DB_USER: ${DB_USER:-drupal}
      DB_PASSWORD: ${DB_PASSWORD:-dbpassword}
      DB_HOST: "mariadb"
      DB_PORT: "3306"
      DB_DRIVER: "mysql"
      DRUSH_OPTIONS_URI: "${PROJECT_BASE_URL:-idcp.localhost}:8000"
      DRUPAL_HASH_SALT: ${DRUPAL_HASH_SALT:-tfvQNpDFG2CjY9WHGNgFqC3eoMjyg5pZdGMQ74zjmnIoe0bi8F3hUvBWnGFIAM3nnj2iWA}
      NGINX_LISTEN_PORT: 8080
      AUTO_INSTALL: ${DRUPAL_AUTO_INSTALL:-true}
    volumes:
      # set delegated mode here on docker for mac for faster disk I/O
      - ./codebase:${APP_ROOT:-/var/www/app}:delegated
      - ./data/drupal/files:${FILES_DIR:-/mnt/files}
      # Anonymous volumes as a workaround to prevent empty or non existent host
      # folders from accidentally getting mounted in container and overwrite the
      # composer build stage files.
      - ${APP_ROOT:-/var/www/app}/vendor
      - ${APP_DOCROOT:-/var/www/app/web}/modules/contrib
      - ${APP_DOCROOT:-/var/www/app/web}/themes/contrib
      - ${APP_DOCROOT:-/var/www/app/web}/profiles/contrib
      - ${APP_DOCROOT:-/var/www/app/web}/libraries
    labels:
      - "traefik.http.routers.${PROJECT_NAME:-islandora}.rule=Host(`${PROJECT_BASE_URL:-idcp.localhost}`)"
      - "traefik.http.services.${PROJECT_NAME:-islandora}.loadbalancer.server.port=8080"

      
  solr:
    image: solr:$SOLR_TAG
    container_name: "${PROJECT_NAME}_solr"
    ports:
      - "8983:8983"
    volumes:
      - solr-data:/var/solr/data/islandora
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - islandora
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_solr.rule=Host(`solr.${PROJECT_BASE_URL}`)"


  cantaloupe:
    image: lyrasis/cantaloupe:latest # should this be 4.0-1 instead?
    container_name: "${PROJECT_NAME}_cantaloupe"
    # networks:
    #   - internal
    env_file:
      - cantaloupe.env
    ports:
      - "8182:8182"
    # TO DO: Determine what type of container handling is needed, exposed ports etc?
    #volumes:
    # (optional) bind-mount this file as a template for changes to the cantaloupe container. Currently the cantaloupe.env handles this.
    #  - ./config/cantaloupe/cantaloupe.properties:/cantaloupe/cantaloupe.properties
    #labels:
    #  - "traefik.http.routers.${PROJECT_NAME}_cantaloupe.rule=Host(`cantaloupe.${PROJECT_BASE_URL}`)"

  ### MVP2 - Microservices - Start

  ## TO DO: Determine where poppler-utils for generating PDFs is to be located?

  houdini:
    image: borndigital/isle-houdini:mvp2-alpha
    #    build:
    #      context: https://github.com/Islandora-Devops/isle-houdini.git#dev
    #      args:
    #        HOUDINI_JWT_ADMIN_TOKEN: $HOUDINI_JWT_ADMIN_TOKEN
    #        HOUDINI_LOG_LEVEL: $HOUDINI_LOG_LEVEL
    container_name: "${PROJECT_NAME}_houdini"
    # networks:
    #   - internal
    #    ports:
    #      - "8000:8000"
    volumes:
      - ./jwt:/opt/jwt
      - ./config/crayfish/php.ini:/usr/local/etc/php/php.ini
    #labels:
    #  - "traefik.http.routers.${PROJECT_NAME}_houdini.rule=Host(`houdini.${PROJECT_BASE_URL}`)"

  homarus:
    image: borndigital/isle-homarus:mvp2-alpha
    #    build:
    #      context: https://github.com/Islandora-Devops/isle-homarus.git#dev
    #      args:
    #        HOMARUS_JWT_ADMIN_TOKEN: $HOMARUS_JWT_ADMIN_TOKEN
    #        HOMARUS_LOG_LEVEL: $HOMARUS_LOG_LEVEL
    container_name: "${PROJECT_NAME}_homarus"
    #    ports:
    #      - "8001:8000"
    volumes:
      - ./jwt:/opt/jwt
      - ./config/crayfish/php.ini:/usr/local/etc/php/php.ini
    #labels:
    #  - "traefik.http.routers.${PROJECT_NAME}_homarus.rule=Host(`homarus.${PROJECT_BASE_URL}`)"

  hypercube:
    image: borndigital/isle-hypercube:mvp2-alpha
    #    build:
    #      context: https://github.com/Islandora-Devops/isle-hypercube.git#dev
    #      args:
    #        HYPERCUBE_JWT_ADMIN_TOKEN: $HYPERCUBE_JWT_ADMIN_TOKEN
    #        HYPERCUBE_LOG_LEVEL: $HYPERCUBE_LOG_LEVEL
    container_name: "${PROJECT_NAME}_hypercube"
    # networks:
    #   - internal
    #    ports:
    #      - "8002:8000"
    volumes:
      - ./jwt:/opt/jwt
      - ./config/crayfish/php.ini:/usr/local/etc/php/php.ini
    #labels:
    #  - "traefik.http.routers.${PROJECT_NAME}_hypercube.rule=Host(`hypercube.${PROJECT_BASE_URL}`)"

  crayfits:
    image: borndigital/isle-crayfits:mvp2-alpha
    #    build:
    #      context: https://github.com/Islandora-Devops/isle-crayfits.git#dev
    #      args:
    #        FITS_WEBSERVICE_URI: http://fits:8080/fits/examine
    container_name: "${PROJECT_NAME}_crayfits"
    # networks:
    #   - internal
    #    ports:
    #      - "8003:8000"
    volumes:
      - ./config/crayfish/php.ini:/usr/local/etc/php/php.ini
    #labels:
    #  - "traefik.http.routers.${PROJECT_NAME}_hypercube.rule=Host(`hypercube.${PROJECT_BASE_URL}`)"

  fits:
    image: harvardlts/fitsservlet_container:1.5.0
    container_name: "${PROJECT_NAME}_fits"
    # networks:
    #   - internal
  #    ports:
  #      - '8085:8080'
  # TO DO: Determine what type of container handling is needed, exposed ports etc?
  #volumes:
  #labels:
  #  - "traefik.http.routers.${PROJECT_NAME}_fits.rule=Host(`fits.${PROJECT_BASE_URL}`)"

  ### MVP2 - Microservices - End

  traefik:
    # review https://hub.docker.com/_/traefik
    image: traefik:2.1.3
    command: --api.insecure=true --providers.docker
    ports:
      - "8000:80"
      #- "443:443"
      #- "8080:8080"
    volumes:
      # TO DO: Update according to new Traefik 2.0 conventions (values below based on 1.7.9, are incomplete & wrong due to missing "routing" labels)
      - /var/run/docker.sock:/var/run/docker.sock
      # SSL Choice 1: To use Let's Encrypt for SSL- uncomment ONLY the line below and then create an empty config/traefik/acme.json file
      # - ./config/traefik/acme.json:/acme.json
      # SSL Choice 2: To use commercial SSLs - uncomment ONLY the line below. Add your SSL certs (.cert, .pem, .key) files to config/traefik/ssl-certs
      # - ./config/traefik/ssl-certs:/certs:ro
      # Use Environment variables to pass in Traefik config; no traefik.yml required
      # by providers
      # Alternative to a static configureation /etc/traefik/traefik.yml"
      # Pass in config via flags or environment variables
      # https://docs.traefik.io/getting-started/configuration-overview
      # Obsolete - "./config/traefik/traefik.local.yml:/etc/traefik/traefik.yml"

  alpaca-connector:
    container_name: "${PROJECT_NAME}_alpaca"
    image: birkland/isle-alpaca@sha256:9fdf260df79b38fd240192ec618e4eec74cca2b6157b4e59f7d4792295cfe210
    env_file: .env
    # networks:
    #   - internal

  activemq:
    image: rmohr/activemq
    container_name: "${PROJECT_NAME}_activemq"
    env_file: .env
    ports:
      - "8161:8161" # To make mgmt console available for dev purposes.  use admin:admin to log in
    # networks:
    #   - internal
    volumes:
      - activemq-data:/opt/activemq/data

# networks:
#   internal:
#   external:

volumes:
  # For local database storage persistance we bind mount a local folder.
  # This folder needs to be created prior to docker-compose up or build.
  mariadb-data:
  activemq-data:
  solr-data:
  # isle-dc-postgres-data # Added to prototype but not currently used
